### PR TITLE
Add Path.Lookup

### PR DESCRIPTION
**Pull request by StefH**

### CODE REVIEW

**Comment by zjklee** [comment]
How is this different from build-in `lookup` helper?

**Comment by StefH** [comment]
@zjklee 
Ah. I understand. There's a builtin helper.
But that helper does not allow for 3 arguments with a defaultValue.

So a change could be like:

``` c#
using HandlebarsDotNet.PathStructure;

namespace HandlebarsDotNet.Helpers
{
    public sealed class LookupReturnHelperDescriptor : IHelperDescriptor<HelperOptions>
    {
        public PathInfo Name { get; } = "lookup";

        public object Invoke(in HelperOptions options, in Context context, in Arguments arguments)
        {
            if (arguments.Length != 2 && arguments.Length != 3)
            {
                throw new HandlebarsException("{{lookup}} helper must have two or three arguments");
            }

            var segment = ChainSegment.Create(arguments[1]);

            var defaultValueIfNotFound = arguments.Length == 3 ? arguments[2] : UndefinedBindingResult.Create(segment);
            
            return !options.TryAccessMember(arguments[0], segment, out var value)
                ? defaultValueIfNotFound
                : value;
        }

        public void Invoke(in EncodedTextWriter output, in HelperOptions options, in Context context, in Arguments arguments)
        {
            output.Write(Invoke(options, context, arguments));
        }
    }
}
```

**Comment by zjklee** [comment]
@StefH , looks good to me 🙂

**Comment by StefH** [comment]
@zjklee Shall I create a PR for Handlebars.Net ?

**Comment by StefH** [comment]
@zjklee See PR https://github.com/Handlebars-Net/Handlebars.Net/pull/542

**Pull request merged**
