### PR TITLE
System.TypeLoadException : Could not load type 'HandlebarsDotNet.Poly…

### PR DESCRIPTION
**Pull request by caoko**
…fills.AsyncLocal`1'

- https://github.com/Handlebars-Net/Handlebars.Net.Helpers/issues/65

### CODE REVIEW

**Comment by StefH** [comment]
@caoko 
It seems that you broke the unit tests?
```
[xUnit.net 00:00:06.69]     HandlebarsDotNet.Helpers.Tests.Helpers.HumanizerHelpersTests.Truncate(length: 2, separator: null, truncator: "FixedNumberOfWords", truncateFrom: null, expected: "Long text?") [FAIL]
   Expected result to be 
"Long text?", but 
"Long text…" differs near "…" (index 9).
```

Can you please revert the changes to the unit-tests?

(Maybe you are running locally in a different Culture?)

**Comment by caoko** [comment]
> @caoko It seems that you broke the unit tests?
> 
> ```
> [xUnit.net 00:00:06.69]     HandlebarsDotNet.Helpers.Tests.Helpers.HumanizerHelpersTests.Truncate(length: 2, separator: null, truncator: "FixedNumberOfWords", truncateFrom: null, expected: "Long text?") [FAIL]
>    Expected result to be 
> "Long text?", but 
> "Long text…" differs near "…" (index 9).
> ```
> 
> Can you please revert the changes to the unit-tests?
> 
> (Maybe you are running locally in a different Culture?)

Yes, it seems to be a file encoding problem.
File encoding should be utf-8...

You can ignore the changes.

**Comment by StefH** [comment]
@caoko 
Can you revert these changes to that file please?

**Comment by caoko** [comment]
yes. reverted these file.

**Pull request merged**
